name: Deploy to Staging

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Staging Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.JCC_STAGING_KEY }}

      - name: Deploy to Staging Server
        run: |
          echo "Attempting SSH connection to staging server..."
          ssh -v -o StrictHostKeyChecking=no ${{ secrets.JCC_STAGING_USER }}@${{ secrets.JCC_STAGING_HOST }} "echo ✅ SSH successful! Ready for deployment."
